name:                kanji
version:             3.1.0
synopsis:            Perform 漢字検定 (Japan Kanji Aptitude Test) level analysis on Japanese Kanji.
description:         Perform 漢字検定 (Japan Kanji Aptitude Test) level analysis on Japanese Kanji.
homepage:            https://github.com/fosskers/kanji
license:             BSD3
author:              Colin Woodbury
maintainer:          colingw@gmail.com
copyright:           2011 - 2018 Colin Woodbury
category:            Data

extra-source-files:
  - README.md
  - CHANGELOG.md

ghc-options:
  - -fwarn-unused-imports
  - -fwarn-unused-binds
  - -fwarn-name-shadowing
  - -fwarn-unused-matches
  - -fwarn-incomplete-patterns
  - -fwarn-incomplete-uni-patterns

dependencies:
  - base >= 4.7 && < 5
  - containers
  - text

library:
  source-dirs: lib
  other-modules: []

executables:
  kanji:
    source-dirs: nanq
    main: nanq.hs
    other-modules: []
    dependencies:
      - kanji
      - aeson >= 1.2 && < 1.3
      - aeson-pretty
      - extensible-effects >= 2.1 && < 2.2
      - microlens >= 0.4 && < 0.5
      - microlens-platform
      - microlens-aeson >= 2.2 && < 2.3
      - optparse-applicative >= 0.14 && < 0.15
