name:                kanji
version:             3.1.0
synopsis:            Perform 漢字検定 (Japan Kanji Aptitude Test) level analysis on Japanese Kanji
description:         Perform 漢字検定 (Japan Kanji Aptitude Test) level analysis on Japanese Kanji.
homepage:            https://github.com/fosskers/kanji
license:             BSD3
author:              Colin Woodbury
maintainer:          colingw@gmail.com
copyright:           2011 - 2018 Colin Woodbury
category:            Data

extra-source-files:
  - README.md
  - CHANGELOG.md

ghc-options:
  - -fwarn-unused-imports
  - -fwarn-unused-binds
  - -fwarn-name-shadowing
  - -fwarn-unused-matches
  - -fwarn-incomplete-patterns
  - -fwarn-incomplete-uni-patterns

dependencies:
  - base >= 4.7 && < 5
  - aeson >= 1.2 && < 1.4
  - containers
  - text

library:
  source-dirs: lib
  other-modules: []
  dependencies:
    - deepseq
    - hashable

tests:
  kanji-test:
    main: Test.hs
    source-dirs: test
    other-modules: []
    ghc-options:
      - -threaded
    dependencies:
      - kanji
      - HUnit-approx >= 1.1 && < 1.2
      - tasty >= 0.11 && < 1.1
      - tasty-hunit >= 0.9 && < 0.11

benchmarks:
  kanji-bench:
    main: Bench.hs
    source-dirs: bench
    other-modules: []
    ghc-options:
      - -threaded
      - -O2
    dependencies:
      - kanji
      - criterion >= 1.1 && < 1.5

executables:
  kanji:
    source-dirs: nanq
    main: nanq.hs
    other-modules: []
    default-extensions:
      - NoImplicitPrelude
      - OverloadedStrings
    ghc-options:
      - -O2
    dependencies:
      - kanji
      - aeson-pretty
      - microlens >= 0.4 && < 0.5
      - microlens-platform
      - microlens-aeson >= 2.2 && < 2.4
      - optparse-applicative >= 0.14 && < 0.15
      - protolude >= 0.2 && < 0.3
